"""Create Messages

Revision ID: 3d5a4f21a517
Revises: 
Create Date: 2022-05-15 00:33:32.482896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d5a4f21a517"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("rowid", sa.Integer(), nullable=False),
        sa.Column("room", sa.Text(), nullable=False),
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("emblem", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("flags", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_ts", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("rowid"),
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_message_deleted"), ["deleted"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_deleted_ts"), ["deleted_ts"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_flags"), ["flags"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_room"), ["room"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_ts"), ["ts"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_username"), ["username"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_username"))
        batch_op.drop_index(batch_op.f("ix_message_ts"))
        batch_op.drop_index(batch_op.f("ix_message_room"))
        batch_op.drop_index(batch_op.f("ix_message_flags"))
        batch_op.drop_index(batch_op.f("ix_message_deleted_ts"))
        batch_op.drop_index(batch_op.f("ix_message_deleted"))

    op.drop_table("message")
    # ### end Alembic commands ###
