"""Create message

Revision ID: 420ff2a8e514
Revises: 
Create Date: 2022-05-15 02:20:03.607565

"""
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "420ff2a8e514"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("rowid", sa.Integer(), nullable=False),
        sa.Column("room", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("ts", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("emblem", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("flags", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_ts", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("rowid"),
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_message_deleted"), ["deleted"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_deleted_ts"), ["deleted_ts"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_flags"), ["flags"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_message_id"), ["id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_message_room"), ["room"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_ts"), ["ts"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_username"), ["username"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_username"))
        batch_op.drop_index(batch_op.f("ix_message_ts"))
        batch_op.drop_index(batch_op.f("ix_message_room"))
        batch_op.drop_index(batch_op.f("ix_message_id"))
        batch_op.drop_index(batch_op.f("ix_message_flags"))
        batch_op.drop_index(batch_op.f("ix_message_deleted_ts"))
        batch_op.drop_index(batch_op.f("ix_message_deleted"))

    op.drop_table("message")
    # ### end Alembic commands ###
