"""

Revision ID: 52f2a3e57590
Revises: 420ff2a8e514
Create Date: 2022-06-12 21:27:43.126754

"""
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "52f2a3e57590"
down_revision = "420ff2a8e514"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firebase_uid", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_firebase_uid"), ["firebase_uid"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_user_id"), ["id"], unique=False)

    op.create_table(
        "user_snapshot",
        sa.Column("rowid", sa.Integer(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("ts", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("is_farmhand", sa.Boolean(), nullable=False),
        sa.Column("is_ranger", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("rowid"),
    )
    with op.batch_alter_table("user_snapshot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_snapshot_username"), ["username"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_snapshot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_snapshot_username"))

    op.drop_table("user_snapshot")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_firebase_uid"))

    op.drop_table("user")
    # ### end Alembic commands ###
