"""Firebase UID is optional

Revision ID: a3542154dbaa
Revises: 52f2a3e57590
Create Date: 2022-06-14 14:31:28.855440

"""
from alembic import op
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "a3542154dbaa"
down_revision = "52f2a3e57590"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "firebase_uid", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "firebase_uid", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###
